name: Cucumber Tests
on:
  pull_request:
jobs:
  playwright-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies and Playwright
      shell: bash
      run: |
        npm ci
        npx playwright install --with-deps chromium
    - name: Run Api Tests
      shell: bash
      run: npx cucumber-js tests/ui/features --parallel 3 --tags "@ui" --config tests/ui/cucumber.js --retry 2
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ui-report
        path: reports/
        retention-days: 30

  api-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Run API tests
      run: npx cucumber-js tests/api/features --config tests/api/cucumber.js --retry 1
      env:
        BASEURL: ${{ secrets.BASEURL }}
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: api-report
        path: reports/
        retention-days: 30
